name: test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1.3
      with:
        envkey_DATABASE_URL: ""
        envkey_GOOGLE_CLIENT_ID: ""
        envkey_GOOGLE_CLIENT_SECRET: ""
        directory: <directory_name>
        file_name: .env
        fail_on_empty: false
    - run: npm install
    - run: npm run build --if-present
    - run: npm test
