name: test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Create dot env file
    - shell: bash
      run: |
        touch .env
        echo "DATABASE_URL=''" >> .env
        echo "GOOGLE_CLIENT_ID=''" >> .env
        echo "GOOGLE_CLIENT_SECRET=''" >> .env
    - run: npm install
    - run: npm run build --if-present
    - run: npm test
